### PR TITLE
[WIP]: use new c-toxcore, use new jvm-toxcore-c and jvm-toxcore-api | switch from libkaliumjni to libsodiumjni

### PR DESCRIPTION
**Pull request by zoff99**
* travis build not working in this version!!
* circleCI build working

https://circleci.com/gh/zoff99/Antox/214#artifacts/containers/0

https://214-57031623-gh.circle-artifacts.com/0/tmp/circle-artifacts.rFT6bq7/Antox_circleci_f921db238ee2b7055e8222686527243a81683aa5.apk

* this build builds: c-toxcore, new jvm-toxcore-c and jvm-toxcore-api from source!!
* this build builds libsodium-jni from source!!

* libs (*.so) are not stripped yet!
* needs tests on android x86 (since i don't have an x86 device)

### CODE REVIEW

**Comment by zoff99** [comment]
also i removed some of the test stuff. to make it work. needs to be added back again later

**Comment by zetok** [comment]
Could you squash those commits?

**Comment by zoff99** [comment]
github webinterface can squash it on merge. if you want to merge

**Comment by zoff99** [comment]
is this now the first client using the new toxcore (and jvm toxcore) ?

**Comment by zetok** [comment]
>is this now the first client using the new toxcore (and jvm toxcore) ?

No, and yes.

µTox and qTox supported c-toxcore since quite a while, and this will make Antox to be the first jvm client to use c-toxcore :)

**Comment by zoff99** [comment]
only if somebody dares to merge my crappy codingstyle :-)
@wiiaam wanna look at this please?

**Pull request closed without merging**
