### PR TITLE
Antox v0.25 (old)

### PR DESCRIPTION
**Pull request by zoff99**
code changes:
=
* use new c-toxcore
* use new jvm-toxore[*]
* should now work with all ARM and x86 Android devices
* use libsodiumjni instead of libkaliumjni
* fix some bugs and crashes
* added fastscroller to chat
* icons and "open"-action for all filetypes
* update to newer google appcompat lib
* crashes are recorded on sdcard as files [can be used to easily open a github issue and attach the stackstrace]
* added highly experimental "BatterySaving mode"
* fixed some filetransfer bugs
* added filetransfer cancel icon and functionality
* fixed "download-dependencies*" scripts to work with new stuff

build changes:
=
* libs are built from source on CircleCI
* app is built on Travis (with .so and .jar libs from latest working CircleCI build)
* can be easily built on Android Studio or commandline gradle [README to follow]

### CODE REVIEW

**Comment by zoff99** [comment]
@wiiaam can you take a look at it and tell me what you think?

**Comment by wiiaam** [comment]
@zoff99 most things look good, there are a couple of things that I'm not sure of though.

For starters I don't really want to be building the dependencies exclusively through circleci, it is much less complicated and more efficient to use the jenkins. Having a buildscript for these would be quite useful though.

Why delete the tests?

Also I noticed that you added some libraries as a source, these need to be obtained through maven to keep the repo cleaner.

**Comment by zoff99** [comment]
you can use jenkins. but i need it like this to be able to switch to a new version of c-toxcore without waiting for updates on 3 other repos. but i does not hurt to build the libs on circleCI so i think it can stay.

as i said the tests can be added again, i had some problems and was not sure if it was the tests. but since no CI system is currently running the tests it does not really matter much. but i can add them back in the next commit

strange argument about source. since github is all source :-)
i don't see any reason to add precompiled jars for stuff that's only a couple of files. anyway the sources are git submodules, so there is only a link in the repo. which libs are you referring exactly here?

so in gerneral you think after some discussion this can be merged? because i rather have it sooner than later, so that people don't make new commits and fixes to the "old" version.

maybe an official branch v0.25 in the Antox repo?

how do you want to proceed?

**Comment by zoff99** [comment]
about using jenkins. that is just not possible. here is why:

antox needs a lot of stuff precompiled:
* libsodiumjni (for at least 2 architectures)
* libtox4j.so (for at least 2 architectures)
* tox4j-c.jar
* tox4j-api.jar

so you need at least 3 different persons and 4 repositories to always build those, otherwise you can not do anything with antox source
also if (as i did here) someone that is not you want to update antox to a newer version of toxcore or to a newer version of libsodiumjni, than that is just 100% not possible now. only the main versions are available pre built. and building them yourself locally every time is very hard, as i found out with jvm-toxcore-c :-)

so i think it's good that antox can be built with any version of toxcore and jvm-toxcore and libsodium without needing repo admin to update their repos and build systems.

that was the long answer :-)

**Comment by dolohow** [comment]
I think you should split commits to individual changes so that everything can be easily tracked down or reverted in a future.

**Comment by louipc** [comment]
On Thu 19 Jan 2017 13:39 -0800, Łukasz Żarnowiecki wrote:
> I think you should split commits to individual changes so that everything can
> be easily tracked down or reverted in a future.

How about like this?
https://github.com/zoff99/Antox/pull/10

I wonder where that merge went in the history...
https://github.com/zoff99/Antox/commits/zoff99/Antox_v0.25
Looks like he merged, rebased and squashed the merge.

Can't really trust these kind of development practices.

**Comment by zoff99** [comment]
@wiiam should those "red" marked versions be 0.1.2 aswell?
what are these exactly?

**Comment by zoff99** [comment]
@wiiaam @subliun did you get a chance to look at it some more? any comments?

**Comment by zoff99** [comment]
use the newer #400

**Pull request closed without merging**
