### PR TITLE
Possible solutions in scala code to increase FPS.

### PR DESCRIPTION
**Pull request by vassad**
Based on the issue #344
https://github.com/Antox/Antox/issues/344#issuecomment-249420860

### CODE REVIEW

**Comment by Mikhael-Danilov** [comment]
Anything wrong with this PR? Any work on it required to be done before merge?

**Comment by zoff99** [comment]
can you also please make this PR to https://github.com/zoff99/Antox/tree/z_new_source
thanks

**Comment by zoff99** [comment]
does this increase FPS for sending or receiving video?

**Comment by vassad** [comment]
hey @zoff99, this increases fps for sending video, but i recommend you to recreate the whole library and bind the java code with JNI - i am experimenting with it from scratch, and now i have 640x480 30 fps on several phones for send/receive video, and 1280x720 up to 20 fps (nexus7 with camera2 doesn't give me more frames in onImageReady than 20fps). The last libtox4j.so which is used in Antox seems to be too slow. Still, the main problem is java/scala conversions, which are propably the main slower component. I also succeeded to use YV12 format for camera - than you don't need any conversions, just pass it to toxcore in Call.scala.

**Comment by zoff99** [comment]
@vassad so does it need a change in https://github.com/TokTok/c-toxcore or in https://github.com/TokTok/jvm-toxcore-c ?

**Comment by vassad** [comment]
only the vpx_img_alloc and triple memcpy in toxav.c. Allocation can be made not every frame, but when the image size is changed. instead of memcpy-ing y,u,v - just pass pointers to the allocated vpx_image - these can save about 5fps on nexus7 2012, may vary on different phones - especially not well hardwared. Still, this is really good not to allocate and copy 3 times per frame such a big amount of data.

But the main slowing factor is java/scala - so continuing this issue, it is good not to call FormatConversions.scala at all - just take .YV12 format from camera - and no need to change VPX format in toxav.

**Comment by zoff99** [comment]
can you make that PR in https://github.com/TokTok/c-toxcore ?
i then can use it to make a debug version of Antox based on v0.25

are you sure every android device can have YV12 format? in that field i am not versed

**Comment by vassad** [comment]
I will make it soon, just after one more check of the efficiency of such a fix.
As for the YV12, it is assumed to be supported for every device since API12.
https://developer.android.com/reference/android/graphics/ImageFormat.html#YV12

**Comment by zoff99** [comment]
@vassad and can you please make this PR against this repo:
https://github.com/zoff99/Antox/tree/zoff99/Antox_v0.25

?

**Comment by vassad** [comment]
@zoff99 created a PR

**Comment by zoff99** [comment]
included in #392

**Pull request merged**
