### PR TITLE
CircleCI small tweaks

### PR DESCRIPTION
**Pull request by zoff99**
provide both same-name apk file and filename with hash
add QR codes for easy testing on phone (scan with phone to download apk file)

### CODE REVIEW

**Comment by zoff99** [comment]
maybe you can login to cirecleci.com just once with your Antox github user?
then all PRs and commit will be automatically built and can be tested easily on phones.

**Comment by wiiaam** [comment]
Just connected it now and running a build. Is it still really necessary to have all the sleeping in it? I can understand waiting a few seconds for an app to start but not 3 minutes

**Comment by zoff99** [comment]
yes, the emulator is very slow. and needs to startup fully.

**Comment by zoff99** [comment]
the CI build should just be to automatically verify that PRs work. and to quickly test it on a phone (via QR code).

i guess nobody should use it for rapid development.

**Pull request merged**
