### PR TITLE
Reconnection every 60 seconds if connection was broken

### PR DESCRIPTION
**Pull request by pchk**
#263 #248

### CODE REVIEW

**Comment by toxtox** [comment]
@pchk 
Thanks for your pull request. Did you try your patch even without orbot? In my case I use my mobile phone as a mobile device ;-) and I have several connection interruptions every day (just normal) and after every interruption / brake I have to logout and login into Antox again in order to reconnect. Therefore my hope is that your patch could make Antox suitable for daily use for me and others :-) :+1:

**Comment by pchk** [comment]
@toxtox that patch is not fior orbot compability. 
It adds reconnection on any network type and configuration generally. 
So it should help anyway.

**Comment by toxtox** [comment]
@pchk  Thanks for your answer. I guess your patch could be a bigger step forward concerning network reliability and could be the solution for several posted bugs.

**Comment by toxtox** [comment]
@pchk The last update of Antox is more than a month ago. I guess the implementation of your patch will take some more time. **Is there a way you could offer an unofficial Antox binary of your fork (just for testing purposes)?** Maybe at "_**Jenkins**_"? Last December the binaries of the Antox-A/V-Version were publicated at Jenkins as separate project, too.

**Comment by pchk** [comment]
@toxtox i think that there will be some places for future improvements for stable connection.
But i need to do a small research to find some free build environments available over the net. Right now i found TravisCI. Looks like it is possible to use it for build the fork.

**Comment by zoff99** [comment]
free build environment:

merge  #293 and build it with circleCI

**Comment by pchk** [comment]
@zoff99 thanks, yeah, i saw your pull request. And even tried to setup circleCI for my fork using your commands for dependencies and build. Right now i am stuck with commons-imaging resolving. It cant be done due to maintenance of apache snapshots repo. 
Want to drop that dependency, just need to write own EXIF stripper for JPEG.

**Comment by zoff99** [comment]
@pchk do you mean it does not build with circleCI ?
if you fork from my PR it should work.

can you post the link to your circle build result page?

**Comment by pchk** [comment]
@zoff99 you can check that https://repository.apache.org/content/repositories/snapshots right now is unavailable. Our dependencies from that repo could not be resolved.

**Comment by zoff99** [comment]
my build is working fine:
https://circleci.com/gh/zoff99/Antox/96#artifacts

**Comment by pchk** [comment]
According to logs Looks like you was lucky to get it into gradile cache before the repo becomes unavailable)
Anyway will get your circle.yml

**Comment by pchk** [comment]
@zoff99 hmm, obviously im missing something. Took your circle.yml and it works fine.

**Comment by toxtox** [comment]
@pchk 
Thanks for offering a binary of your fork so fast.
I made some investigations with your patched antox.apk.

This is what I could find out:

- my own Antox profile is always online again in less than 64 seconds after switching wifi on (**This is an improvement compared to prior versions**)

- But the reconnect delay of my contacts depends on the duration of the interruption. This means: If the interruption duration was only 60 seconds the delay of my contacts are the same compared to the delay of my own profile. If the interruption durations before were 240 seconds and longer the behaviour was unreliable. The reconnection delays of the contacts increased with the interruption duration. Three tests with 270 seconds and more interruption duration failed. Only one test with 380 seconds interruption duration passed with a contacts reconnect delay of 112 seconds. After each failed contacts reconnection attempt I had to manually logout and login again.

- The results concerning the reconnection delays of the contact names are very similar to my prior test results with prior Antox versions including 0.23.98. (see #217 )

I hope my results are not too complicated. If something is unclear or incomplete please ask me.

times in [seconds]
                                                                
test | Interruption duration | Antox reconnect delays -> | own profile | contacts
------ | ------------------------------- | ---------------------------------------- | ----------------- | -------------
1     |          300                 |	                                    |  30             |     105
2     |          300	         |                                          |  17	        | failed test aborted after 240
       | logout/login	         |                                          |                   |		
3     |            60                 |                                          |  30	        |       30
4     |            60	         |                                          |  26	        |       26
5     |            60	         |                                          |  25	        |       25
6     |          380	         |                                          |  29	        |      112
7     |          390                 |                                          |    5	        | failed test aborted after 500
       | logout/login	         |	                                    |		        |
8     |          240	         |                                          |   24	        |        76
9     |          270	         |                                          |   64	        | failed test aborted after 360

**Comment by zoff99** [comment]
@wiiaam: can you merge my PR #293 ?

**Comment by zoff99** [comment]
@pchk if you use my complete PR #293 it will create a toxid and add groupbot, and wait for groupbot to accept.
i think this could easily be extented to simulate interruptions on the emulator

**Comment by pchk** [comment]
@toxtox great deal! Yeah, im inspecting that behavior. Think i will fix that soon.
@zoff99 no, i just merged your https://github.com/Antox/Antox/pull/293/commits/fdf2fbd3a8c3fbdad95342da79e1ac2d7af37ce0.
What stopped me to merge the whole PR is that i don't want to change main application logic for functional test's purposes. 
Of course we need auto-tests. But they should "live" outside of main code.

**Comment by zoff99** [comment]
i disagree a bit on the tests. it should be tested automatically on an emulator using the actual code (just as is a user would do it).
of course you need unit tests aswell. but for example a problem like this #292 can't be tested with unit tests.

**Comment by toxtox** [comment]
@pchk 
**Could you already inspect the behaviour described in the results-table?**
> Yeah, im inspecting that behavior. Think i will fix that soon.

In the mean time user **qasmoke** tryed to reproduce this behaviour but he came to a slightly different result #297 : In his investigation the behaviour depends on the reason for the data interruption. If the (mobile) data interruption is caused by switching off and on wifi on the phone Antox always reconnects even after a longer interruption. BUT if he (mobile) data interruption is caused by switching off and on wifi at the router Antox stays offline.

**Could it be that the behaviour depends additionally on the Android- and/or custom rom version?**

By the way the results in my results-table above are based on a _Cyanogenmod_ **CM13** ROM (Android **6.01**). But I saw exactly the same behaviour on a _ArchiDroid_ **V3.0.2** ROM (based on **CM11** Android **4.4.4**)

**Comment by aaannndddyyy** [comment]
Thank you, this one improved my user experience.

**Pull request merged**
