### PR TITLE
Antox v0.25.1

### PR DESCRIPTION
**Pull request by zoff99**

### CODE REVIEW

**Comment by wiiaam** [comment]
You still need to squash a lot of these commits down as its kinda hard to review it like this

**Comment by wiiaam** [comment]
Couple more things

- https://github.com/zoff99/Antox/tree/zoff99/Antox_v0.25.1/app/src/main/java/chat/tox/antox
This isn't C, classes need to be in a folder heirachy not just thrown in the main package. Also the repo is scala so I will be converting it all to scala eventually and placing these with the rest of the classes, with the exception of external classes.

- println shouldn't be used for debugging in android, the correct way is to use [Log](https://developer.android.com/reference/android/util/Log.html). Antox has its own implementation called AntoxLog

**Comment by wiiaam** [comment]
Now merged into master, with the exception of your latest line of commits, as I already told you to stop adding to the PR

**Comment by wiiaam** [comment]
Also can you stop reformatting self closing tags to remove the space before the slash? 
`` will always look better than ``, plus its a part of the XHTML guidelines

**Comment by Astonex** [comment]
@zoff99 Do not have so much work and so many commits in a single PR. A single PR should fix a single problem, or implement a single feature. If you work on multiple bug fixes and multiple features, you should create multiple PRs.

**Comment by zoff99** [comment]
we talked about this on IRC

**Comment by louipc** [comment]
On Tue 07 Feb 2017 03:27 -0800, Mark Winter wrote:
> @zoff99 Do not have so much work and so many commits in a single PR. A single
> PR should fix a single problem, or implement a single feature. If you work on
> multiple bug fixes and multiple features, you should create multiple PRs.

More descriptive commit messages would be great too.

**Pull request closed without merging**
