### PR TITLE
Update export profil function to work with android 6 permission way

### PR DESCRIPTION
**Pull request by bodtx**
This is linked with #199
Tested on my motorola G3 android 6.0
TODO : Maybe have to check the permissions on a special object

### CODE REVIEW

**Comment by wiiaam** [comment]
Looks good, will test and merge tomorrow night.

Just one thing on line 135-137, why does it request two different permissions?

There are some other permission issues that need to be addressed, like importing profiles, and file transfers. Any help on this would also be greatly appreciated.

**Comment by bodtx** [comment]
Hi, indeed the name of MY_PERMISSIONS_REQUEST_READ_CONTACTS is wrong as I past the google exemple. I sould rename it MY_PERMISSIONS_REQUEST_WRITE_STORAGE. but it is just a value for the callback. I will commit on this.
I will try to help you :)

**Comment by wiiaam** [comment]
Sorry for the lateness of the response, I've been fixing a bunch of new bugs from audio being merged.

I've given this a test and it seems that it doesn't actually work until the app is force restarted. I will probably start working on Android 6 permissions on another branch for now until it can all be completed and is merge ready. Whilst your solution does work for the exporting there are many other occurrences where permissions are necessary and I will make a permission utility to stop verbosity.

**Comment by androclus** [comment]
i am not sure if i should post this here or make a new issue, just let me know:

regarding IMport, as well --

I recently switched my Nexus 6 from using stock rom (but rooted) 6.0, to (AOSP-based) Cyanogenmod 13.0.1 (Android 6.0.1 r17).

Before switching (i.e., still on rooted stock rom), I could not import in Antox, because the pop-up interface would not let me navigate DOWN, only up the directory tree. And it didn't show me any files -- only directories.

After switching (to Cyanogenmod), now clicking on "Import Profile" simply results in crashing Antox. :-(

Let me know if you want me to make this a separate issue, or if perhaps the problems with Importing and Exporting on 6.0-based devices derives from the same cause.

**Comment by wiiaam** [comment]
Closing for now as I am working on permissions on a new branch https://github.com/Antox/Antox/tree/6-permissions

**Pull request closed without merging**
