### PR TITLE
add Automated tests

### PR DESCRIPTION
**Pull request by zoff99**
if debug flag is set:

login and add Groupbot.
make screenshot.

### CODE REVIEW

**Comment by zoff99** [comment]
maybe even consider to set "wifi_only" default to "false"
most people will use 3g on a phone

**Comment by pchk** [comment]
Yeah, i think nobody cares about traffic limits nowadays with 3G and LTR networks spread worldwide

**Comment by cebe** [comment]
traffic limits are an issue in many countries. 3g means its fast but you may reach limit faster so there is no win ;)

**Comment by zoff99** [comment]
this PR is actually only about circleCI and automated tests for that.
it does not change anything in normal builds.
wifi_only flag was just as a comment. sorry if it was misleading

**Comment by zoff99** [comment]
https://circleci.com/gh/zoff99/Antox/86#artifacts

proof that it's running in the emulator:
https://circle-artifacts.com/gh/zoff99/Antox/86/artifacts/0/tmp/circle-artifacts.RXQgJxH/capture002.png
capture002

**Comment by wiiaam** [comment]
If this PR is including the circle ci buildscript then you should either demerge the branch or close the other. Would you also mind squashing down some of the commits.

**Comment by zoff99** [comment]
if you will merge it , then yes.

**Comment by zoff99** [comment]
new PR -->  #293

**Pull request closed without merging**
