### PR TITLE
circleCI and automated tests

### PR DESCRIPTION
**Pull request by zoff99**
less commits

https://circleci.com/gh/zoff99/Antox/95#artifacts

https://circle-artifacts.com/gh/zoff99/Antox/95/artifacts/0/tmp/circle-artifacts.sUF2Mdz/capture002.png

capture002

### CODE REVIEW

**Comment by zoff99** [comment]
any news on this?

**Comment by wiiaam** [comment]
I'm currently away from home for a bit and don't have a test environment available, but I should be back in a few days and can catch up on a lot of this stuff

**Comment by wiiaam** [comment]
Still `sleep`ing, will need to reduce the amount of these so it doesn't take 20 minutes to complete

Things like [line 115](https://github.com/zoff99/Antox/blob/fdf2fbd3a8c3fbdad95342da79e1ac2d7af37ce0/circle.yml#L115) where you are sleeping after it has been blocking for the bootup. 

Also don't modify source code for adding tests, all tests should be using junit. Examples of these can be found [here](https://github.com/Antox/Antox/tree/6-permissions/app/src/androidTest/scala/chat/tox/antox/tests)

**Comment by zoff99** [comment]
ok then don't merge it.

**Comment by wiiaam** [comment]
Note that the circleci script was merged in with pr https://github.com/Antox/Antox/pull/291. The circleci stuff actually looks quite good although I will not be able to do much with it unless @subliun shows his face once in a while.

**Pull request closed without merging**
