### PR TITLE
More ideomatic scala code.

### PR DESCRIPTION
**Pull request by kurnevsky**
What do you think about fixing this?
It's a bad practice to use return statements in scala, so I removed a lot of returns. Also fixed other places a bit.

### CODE REVIEW

**Comment by wiiaam** [comment]
Contributions like these have definitely been needed, seems like these are common occurrences on scala based projects where devs are mostly used to java idioms. Currently the codebase is pretty messy and is long due a proper cleanup.

Also fixed an issue with the Hex conversion you provided, https://github.com/Antox/Antox/commit/61aaea07039456147957fdf0fd37033f6ca75ac8

**Comment by kurnevsky** [comment]
Ok, then I will continue. One thing that I'd like to try - migrate to sbt from gradle. It will allow to have typesafe findViewById and use the latest sdk.

**Comment by kurnevsky** [comment]
btw, I think I saw hex conversion functions in scala tox wrapper somewhere, maybe it's better to use them.

**Comment by kurnevsky** [comment]
Looked at your changes - if you write %02x then it will generate lower case letters, but original code generated upper case.

**Comment by wiiaam** [comment]
@kurnevsky Not sure why, but the uppercase one wasn't working for me, might try it out later though. 
Also, I'm not really a fan of sbt. I find that it is just too slow, and, ironically, gradle is a lot more simpler

**Pull request merged**
