### PR TITLE
small updates to allow fullsource compile

### PR DESCRIPTION
**Pull request by zoff99**
just a small tweak:
* libsodiumjni source link (its just a git submodule link, so no harm)
* .travis.yml will recognize if the branchname has "fullsource" somewhere in the name
* fullsource directory for info and script to allow fullsource compile

your CI stuff and code is in no way changed or touched

### CODE REVIEW

**Comment by zoff99** [comment]
@wiiaam also please activate travis builds for "Antox" repo

**Comment by wiiaam** [comment]
Whats the need to build libsodiumjni by hand? Its only used for toxme, nothing else

**Comment by licaon-kter** [comment]
I guess this (full source compiling) is needed for main F-Droid inclusion.

**Comment by zoff99** [comment]
2 fold.
a) i want to be able to build all used native libs from source
b) its needed to have native libs for the exact same ABIs, or it wont work

also it does not hurt

**Comment by wiiaam** [comment]
I already told you I was reluctant on building tox4j on circle as it is silly to test a version of a library that users may not even be using. Since these are main libraries that the app relies on then it can stay. But there is no need to be building libsodiumjni, even if it does contain ndk libraries, as every user will be using the same version from maven. If you keep trying to push this then I will revert the circleci build back to the way it was (using dependencies from jenkins).

@licaon-kter Not planning on adding to main fdroid repo until app is in release

**Comment by zoff99** [comment]
"If you keep trying to push this then I will revert the circleci build back to the way it was"
nice

**Pull request closed without merging**
